# dtdinstaller level configuration makefile 
 
MAKEFILE = /sf/tools/homescreentools/dtdinstaller/makefile

# Place the first target as the default target which is executed from this level 
dtdinstaller_all :: dtdinstaller_config
  
include include_template.mk